name: Run API Tests

on:
  push:
    branches:
      - main

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

jobs:
  run-api-tests:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repo
        uses: actions/checkout@v3

      # Step 2: Setup Node.js 24
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '24'

      # Step 3: Install Newman globally
      - name: Install Newman
        run: npm install -g newman newman-reporter-html

      # Step 4: List repo files for debugging
      - name: List repo files
        run: ls -la

      # Step 5: Run Newman tests if files exist
      - name: Run Newman tests
        run: |
          if [[ -f collection.json && -f qa-env.json ]]; then
            echo "Running Newman tests..."
            newman run collection.json -e qa-env.json -r cli,html --reporter-html-export report.html || true
          else
            echo "Error: collection.json or qa-env.json not found!"
            exit 1
          fi
          
      # Step 6: Upload HTML report
      - name: Upload API Test Report
        uses: actions/upload-artifact@v4
        with:
          name: api-test-report
          path: report.html




# Step 7 : AI assistant

  ai-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ai-testing/requirements.txt

      - name: Generate AI Test Cases
        run: python ai-testing/generate_tests.py

      - name: Run AI Tests
        run: python ai-testing/run_tests.py

      - name: Upload AI Test Report
        uses: actions/upload-artifact@v4
        with:
          name: ai-test-report
          path: ai-testing/reports/
